version: '3.8'

services:
  frontend:

    restart: unless-stopped
    image: bog_fe
    container_name: frontend
    ports:
      - 8905:80
    depends_on:  
      - backend

  backend:

    restart: unless-stopped
    image: bog_be
    container_name: backend
    ports:
      - 28005:8080
    depends_on:
      - db

  db:

    restart: unless-stopped
    image: postgres:10-alpine
    container_name: database
    ports:
      - 38005:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "image_post_db" 